"""Install a local opencode plugin that registers the ember MCP server.

Register-only: the plugin injects the `mcp.ember` entry on every opencode launch
(via the V1 `config` hook), with an absolute command path and an explicit PATH so
it survives opencode being launched from a GUI with a stripped environment.
The server itself stays lazy — it is started on first tool call.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from string import Template

PLUGIN_FILENAME = "ember.js"

_TEMPLATE = Template(
    """// Generated by `ember init --opencode`. Do not edit by hand.
const COMMAND = $command
const ENVIRONMENT = $environment

export const EmberPlugin = async () => ({
  config: async (config) => {
    config.mcp = config.mcp ?? {}
    config.mcp["ember"] = {
      type: "local",
      command: COMMAND,
      enabled: true,
      timeout: 30000,
      environment: ENVIRONMENT,
    }
  },
})
"""
)


def render(command: list[str], server_url: str, autostart: str = "1") -> str:
    """Render the opencode plugin's JavaScript source.

    Parameters
    ----------
    command : list[str]
        Argv used to launch the MCP server.
    server_url : str
        Value for the ``EMBER_SERVER_URL`` environment variable.
    autostart : str, optional
        Value for the ``EMBER_AUTOSTART`` environment variable. Defaults to
        ``"1"``.

    Returns
    -------
    str
        The rendered plugin source, ready to write to disk.
    """
    environment = {
        "EMBER_SERVER_URL": server_url,
        "EMBER_AUTOSTART": autostart,
    }
    if os.environ.get("PATH"):
        environment["PATH"] = os.environ["PATH"]
    return _TEMPLATE.substitute(
        command=json.dumps(command),
        environment=json.dumps(environment, indent=2),
    )


def plugin_dir(scope: str, project_root: Path | None = None) -> Path:
    """Return the directory the opencode plugin is installed into.

    Parameters
    ----------
    scope : str
        ``"global"`` for the user's opencode config directory, otherwise a
        project-local install.
    project_root : Path | None, optional
        Root to install under when ``scope`` is not ``"global"``; defaults
        to the current working directory.

    Returns
    -------
    Path
        The plugin directory for the given scope.
    """
    if scope == "global":
        return Path.home() / ".config" / "opencode" / "plugins"
    root = project_root or Path.cwd()
    return root / ".opencode" / "plugins"


def install(
    command: list[str],
    server_url: str,
    scope: str = "project",
    project_root: Path | None = None,
) -> Path:
    """Render and write the opencode plugin file.

    Parameters
    ----------
    command : list[str]
        Argv used to launch the MCP server.
    server_url : str
        Value for the ``EMBER_SERVER_URL`` environment variable.
    scope : str, optional
        ``"project"`` (default) or ``"global"``.
    project_root : Path | None, optional
        Root to install under when ``scope`` is ``"project"``; defaults to
        the current working directory.

    Returns
    -------
    Path
        The plugin file path written to.
    """
    directory = plugin_dir(scope, project_root)
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / PLUGIN_FILENAME
    path.write_text(render(command, server_url))
    return path
