"""Install a local opencode plugin that registers the Clef MCP server.

Register-only: the plugin injects the `mcp.clef` entry on every opencode launch
(via the V1 `config` hook), with an absolute command path and an explicit PATH so
it survives opencode being launched from a GUI with a stripped environment.
The server itself stays lazy — it is started on first tool call.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from string import Template

PLUGIN_FILENAME = "clef.js"

_TEMPLATE = Template(
    """// Generated by `clef init --opencode`. Do not edit by hand.
const COMMAND = $command
const ENVIRONMENT = $environment

export const ClefPlugin = async () => ({
  config: async (config) => {
    config.mcp = config.mcp ?? {}
    config.mcp.clef = {
      type: "local",
      command: COMMAND,
      enabled: true,
      timeout: 30000,
      environment: ENVIRONMENT,
    }
  },
})
"""
)


def render(command: list[str], server_url: str, autostart: str = "1") -> str:
    environment = {
        "CLEF_SERVER_URL": server_url,
        "CLEF_AUTOSTART": autostart,
    }
    if os.environ.get("PATH"):
        environment["PATH"] = os.environ["PATH"]
    return _TEMPLATE.substitute(
        command=json.dumps(command),
        environment=json.dumps(environment, indent=2),
    )


def plugin_dir(scope: str, project_root: Path | None = None) -> Path:
    if scope == "global":
        return Path.home() / ".config" / "opencode" / "plugins"
    root = project_root or Path.cwd()
    return root / ".opencode" / "plugins"


def install(
    command: list[str],
    server_url: str,
    scope: str = "project",
    project_root: Path | None = None,
) -> Path:
    directory = plugin_dir(scope, project_root)
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / PLUGIN_FILENAME
    path.write_text(render(command, server_url))
    return path
